name: 'Setup Environment'
description: 'Setup Node.js, Deno, and cache dependencies'

inputs:
  node-version:
    description: 'Node.js version'
    required: false
    default: '20.18.1'
  deno-version:
    description: 'Deno version'
    required: false
    default: '2.2.5'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: ${{ inputs.deno-version }}

    - name: Cache Node.js dependencies
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: node-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          node-${{ runner.os }}-

    - name: Cache Deno dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/deno/deps
          ~/.cache/deno/npm
        key: deno-${{ runner.os }}-${{ hashFiles('supabase/functions/**/deno.lock') }}
        restore-keys: |
          deno-${{ runner.os }}-

    - name: Install dependencies
      shell: bash
      run: npm ci

    - name: Warm up Deno cache
      shell: bash
      working-directory: ./supabase/functions
      run: |
        for lock in */deno.lock; do
          if [ -f "$lock" ]; then
            echo "Caching dependencies for $lock"
            deno cache --lock="$lock" --lock-write
          fi
        done