name: 'Build Application'
description: 'Build the application with environment variables'

inputs:
  supabase-url:
    description: 'Supabase URL'
    required: true
  supabase-anon-key:
    description: 'Supabase anonymous key'
    required: true
  git-sha:
    description: 'Git commit SHA'
    required: true
  sentry-dsn:
    description: 'Sentry DSN'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Build application
      shell: bash
      run: npm run build
      env:
        VITE_SUPABASE_URL: ${{ inputs.supabase-url }}
        VITE_SUPABASE_ANON_KEY: ${{ inputs.supabase-anon-key }}
        VITE_GIT_SHA: ${{ inputs.git-sha }}
        VITE_SENTRY_DSN: ${{ inputs.sentry-dsn }}